routes/web.php
<?php

// Route::get('nosotros', 'PagesController@about')->name('pages.about');
// Route::get('archivo', 'PagesController@archive')->name('pages.archive');
// Route::get('contacto', 'PagesController@contact')->name('pages.contact');

// Route::get('blog/{post}', 'PostsController@show')->name('posts.show');
// Route::get('categorias/{category}', 'CategoriesController@show')->name('categories.show');
// Route::get('tags/{tag}', 'TagsController@show')->name('tags.show');

Route::group([
	'prefix' => 'admin',
	'namespace' => 'Admin',
	'middleware' => 'auth'],
function(){
	Route::get('/', 'AdminController@index')->name('dashboard');

	Route::resource('posts', 'PostsController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('users', 'UsersController', ['as' => 'admin']);
    Route::resource('roles', 'RolesController', ['except' => 'show', 'as' => 'admin']);
    Route::resource('permissions', 'PermissionsController', ['only' => ['index', 'edit', 'update'], 'as' => 'admin']);

    Route::middleware('role:Admin')
    	->put('users/{user}/roles', 'UsersRolesController@update')
    	->name('admin.users.roles.update');

    Route::middleware('role:Admin')
        ->put('users/{user}/permissions', 'UsersPermissionsController@update')
        ->name('admin.users.permissions.update');

	Route::post('posts/{post}/photos', 'PhotosController@store')->name('admin.posts.photos.store');
	Route::delete('photos/{photo}', 'PhotosController@destroy')->name('admin.photos.destroy');

	// rutas de administracion
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/{any?}', 'PagesController@spa')->name('pages.home')->where('any', '.*');

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	protected $fillable = [
        'title', 'body', 'iframe', 'excerpt', 'published_at', 'category_id', 'user_id'
    ];

    protected $dates = ['published_at'];

    protected $appends = ['published_date'];

    protected static function boot()
    {
        parent::boot();

        static::deleting(function($post){
            $post->tags()->detach();
            $post->photos->each->delete();
        });
    }

    public function getRouteKeyName()
    {
        return 'url';
    }

    public function category()
    {
    	return $this->belongsTo(Category::class);
    }

    public function tags()
    {
    	return $this->belongsToMany(Tag::class);
    }

    public function photos()
    {
        return $this->hasMany(Photo::class);
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function scopePublished($query)
    {
        $query->with(['owner', 'category', 'tags', 'photos'])
                ->whereNotNull('published_at')
                ->where('published_at', '<=', Carbon::now() )
                ->latest('published_at');
    }

    public function scopeAllowed($query)
    {
        if( auth()->user()->can('view', $this) )
        {
            return $query;
        }

        return $query->where('user_id', auth()->id());
    }

    public function scopeByYearAndMonth($query)
    {
        return $query->selectRaw('year(published_at) year')
            ->selectRaw('month(published_at) month')
            ->selectRaw('monthname(published_at) monthname')
            ->selectRaw('count(*) posts')
            ->groupBy('year', 'month', 'monthname')
            ->orderBy('published_at');
    }

    public function isPublished()
    {
        return ! is_null($this->published_at) && $this->published_at < today();
    }

    public static function create(array $attributes = [])
    {
        $attributes['user_id'] = auth()->id();

        $post = static::query()->create($attributes);

        $post->generateUrl();

        return $post;
    }

    public function generateUrl()
    {
        $url = str_slug($this->title);

        if ($this->whereUrl($url)->exists())
        {
            $url = "{$url}-{$this->id}";
        }

        $this->url = $url;

        $this->save();
    }

    public function setPublishedAtAttribute($published_at)
    {
        $this->attributes['published_at'] = $published_at ? Carbon::parse($published_at) : null;
    }

    public function setCategoryIdAttribute($category)
    {
        $this->attributes['category_id'] = Category::find($category)
                                ? $category
                                : Category::create(['name' => $category])->id;
    }

    public function syncTags($tags)
    {
        $tagIds = collect($tags)->map(function($tag){
            return Tag::find($tag) ? $tag : Tag::create(['name' => $tag])->id;
        });

        return $this->tags()->sync($tagIds);
    }

    public function getPublishedDateAttribute()
    {
        return optional($this->published_at)->format('M d');
    }

    public function viewType($home = '')
    {
       if ($this->photos->count() === 1):
           return 'posts.photo';
       elseif($this->photos->count() > 1):
           return $home === 'home' ? 'posts.carousel-preview': 'posts.carousel';
       elseif($this->iframe):
           return 'posts.iframe';
       else:
            return 'posts.text';
       endif;
    }
}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Tag;
use App\Post;
use App\Category;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StorePostRequest;

class PostsController extends Controller
{
    public function index()
    {
        $posts = Post::allowed()->get();

    	return view('admin.posts.index', compact('posts'));
    }

    public function store(Request $request)
    {
        $this->authorize('create', new Post);

        $this->validate($request, ['title' => 'required|min:3']);

        $post = Post::create( $request->all() );

        return redirect()->route('admin.posts.edit', $post);
    }

    public function edit(Post $post)
    {
        $this->authorize('update', $post);

        return view('admin.posts.edit', [
            'post' => $post,
            'tags' => Tag::all(),
            'categories' => Category::all()
        ]);
    }

    public function update(Post $post, StorePostRequest $request)
    {
        $this->authorize('update', $post);

        $post->update($request->all());

        $post->syncTags($request->get('tags'));

        return redirect()
            ->route('admin.posts.edit', $post)
            ->with('flash', 'La publicación ha sido guardada');
    }

    public function destroy(Post $post)
    {
        $this->authorize('delete', $post);

        $post->delete();

        return redirect()
            ->route('admin.posts.index')
            ->with('flash', 'La publicación ha sido eliminada');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use App\Http\Resources\PostResource;

class PostsController extends Controller
{
    public function show(Post $post)
    {
        if ($post->isPublished() || auth()->check())
        {
            $post->load('owner', 'category', 'tags', 'photos');

            if (request()->wantsJson())
            {
                return $post;
            }
            return view('posts.show', compact('post'));
        }

        abort(404);
    }
}

resources/views/admin/posts/create.blade.php
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<form method="POST" action="{{ route('admin.posts.store', '#create') }}">
		{{ csrf_field() }}
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Agrega el título de tu nueva publicación</h4>
				</div>
				<div class="modal-body">
					<div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
						{{-- <label>Título de la publicación</label> --}}
						<input id="post-title" name="title"
						class="form-control"
						value="{{ old('title') }}"
						placeholder="Ingresa aquí el título de la publicación" autofocus required>
						{!! $errors->first('title', '<span class="help-block">:message</span>') !!}
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button class="btn btn-primary">Crear publicación</button>
				</div>
			</div>
		</div>
	</form>
</div>

@push('scripts')
	<script>
        if ( window.location.hash === '#create') {
            $('#myModal').modal('show');
        }

        $('#myModal').on('hide.bs.modal', function(){
            window.location.hash = '#';
        });

        $('#myModal').on('shown.bs.modal', function(){
            $('#post-title').focus();
            window.location.hash = '#create';
        });
    </script>
@endpush

resources/views/admin/posts/edit.blade.php
@extends('admin.layout')

@section('header')
	<h1>
		POSTS
		<small>Crear publicación</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
		<li><a href="{{ route('admin.posts.index') }}"><i class="fa fa-list"></i> Posts</a></li>
		<li class="active">Crear</li>
	</ol>
@stop

@section('content')
	<div class="row">
		@if ($post->photos->count())
			<div class="col-md-12">
				<div class="box box-primary">
					<div class="box-body">
						@foreach ($post->photos as $photo)
							<form method="POST" action="{{ route('admin.photos.destroy', $photo) }}">
								{{ method_field('DELETE') }} {{ csrf_field() }}
								<div class="col-md-2">
									<button class="btn btn-danger btn-xs" style="position: absolute">
										<i class="fa fa-remove"></i>
									</button>
									<img class="img-responsive" src="{{ url($photo->url) }}">
								</div>
							</form>
						@endforeach
					</div>
				</div>
			</div>
		@endif
		<form id="post-form" method="POST" action="{{ route('admin.posts.update', $post) }}">
			{{ csrf_field() }} {{ method_field('PUT') }}
			<div class="col-md-8">
				<div class="box box-primary">
					<div class="box-body">
						<div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
							<label>Título de la publicación</label>
							<input name="title"
								   class="form-control"
								   value="{{ old('title', $post->title) }}"
								   placeholder="Ingresa aquí el título de la publicación">
							{!! $errors->first('title', '<span class="help-block">:message</span>') !!}
						</div>
						<div class="form-group {{ $errors->has('body') ? 'has-error' : '' }}">
							<label>Contenido publicación</label>
							<textarea rows="10" name="body" id="editor" class="form-control" placeholder="Ingresa el contendido completo de la publicación">{{ old('body', $post->body) }}</textarea>
							{!! $errors->first('body', '<span class="help-block">:message</span>') !!}
						</div>
						<div class="form-group {{ $errors->has('iframe') ? 'has-error' : '' }}">
							<label>Contenido embebido (iframe)</label>
							<textarea rows="2" name="iframe" id="editor" class="form-control" placeholder="Ingresa contenido embebido (iframe) de audio o video">{{ old('iframe', $post->iframe) }}</textarea>
							{!! $errors->first('iframe', '<span class="help-block">:message</span>') !!}
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="box box-primary">
					<div class="box-body">
						<div class="form-group">
							<label>Fecha de publicación:</label>
							<div class="input-group date">
								<div class="input-group-addon">
									<i class="fa fa-calendar"></i>
								</div>
								<input name="published_at"
									   class="form-control pull-right"
									   value="{{ old('published_at', $post->published_at ? $post->published_at->format('m/d/Y') : null) }}"
									   type="text"
									   id="datepicker">
							</div>
						</div>
						<div class="form-group {{ $errors->has('category_id') ? 'has-error' : '' }}">
							<label>Categorías</label>
							<select name="category_id" class="form-control select2">
								<option value="">Seleciona una categoría</option>
								@foreach ($categories as $category)
									<option value="{{ $category->id }}"
											{{ old('category_id', $post->category_id) == $category->id ? 'selected' : '' }}
									>{{ $category->name }}</option>
								@endforeach
							</select>
							{!! $errors->first('category_id', '<span class="help-block">:message</span>') !!}
						</div>
						<div class="form-group {{ $errors->has('tags') ? 'has-error' : '' }}">
							<label>Etiquetas</label>
							<select name="tags[]" class="form-control select2"
									multiple="multiple"
									data-placeholder="Selecciona una o más etiquetas" style="width: 100%;">
								@foreach ($tags as $tag)
									<option {{ collect(old('tags', $post->tags->pluck('id')))->contains($tag->id) ? 'selected' : '' }} value="{{ $tag->id }}">{{ $tag->name }}</option>
								@endforeach
							</select>
							{!! $errors->first('tags', '<span class="help-block">:message</span>') !!}
						</div>
						<div class="form-group {{ $errors->has('excerpt') ? 'has-error' : '' }}">
							<label>Extracto publicación</label>
							<textarea name="excerpt"
									  class="form-control"
									  placeholder="Ingresa un extracto de la publicación">{{ old('excerpt', $post->excerpt) }}</textarea>
							{!! $errors->first('excerpt', '<span class="help-block">:message</span>') !!}
						</div>
						<div class="form-group">
							<div class="dropzone"></div>
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary btn-block">Guardar Publicación</button>
						</div>
					</div>
				</div>
			</div>
		</form>

	</div>
@stop

@push('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.0.1/dropzone.css">
<link rel="stylesheet" href="/adminlte/plugins/datepicker/datepicker3.css">
<link rel="stylesheet" href="/adminlte/plugins/select2/select2.min.css">
@endpush

@push('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.0.1/min/dropzone.min.js"></script>
<script src="https://cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
<script src="/adminlte/plugins/select2/select2.full.min.js"></script>
<script src="/adminlte/plugins/datepicker/bootstrap-datepicker.js"></script>
<script>
    $('#datepicker').datepicker({
        autoclose: true
    });

    $('.select2').select2({
    	tags: true
    });

    CKEDITOR.replace('editor');
    CKEDITOR.config.height = 315;

    var myDropzone = new Dropzone('.dropzone', {
        url: '/admin/posts/{{ $post->url }}/photos',
        paramName: 'photo',
        acceptedFiles: 'image/*',
        maxFilesize: 2,
        headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
        },
        dictDefaultMessage: 'Arrastra las fotos aquí para subirlas'
    });

    myDropzone.on('error', function(file, res){
        var msg = res.photo[0];
        $('.dz-error-message:last > span').text(msg);
    });

    Dropzone.autoDiscover = false;

</script>
@endpush

resources/views/admin/posts/index.blade.php
@extends('admin.layout')

@section('header')
<h1>
	POSTS
	<small>Listado</small>
</h1>
<ol class="breadcrumb">
	<li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
	<li class="active">Posts</li>
</ol>
@stop

@section('content')
<div class="box box-primary">
	<div class="box-header">
		<h3 class="box-title">Listado de publicaciones</h3>
		<button class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal">
			<i class="fa fa-plus"></i>  Crear publicación
		</button>
	</div>
	<!-- /.box-header -->
	<div class="box-body">
		<table id="posts-table" class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>ID</th>
					<th>Título</th>
					<th>Extracto</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
				@foreach ($posts as $post)
					<tr>
						<td>{{ $post->id }}</td>
						<td>{{ $post->title }}</td>
						<td>{{ $post->excerpt }}</td>
						<td>
							<a href="{{ route('posts.show', $post) }}"
								class="btn btn-xs btn-default"
								target="_blank"
							><i class="fa fa-eye"></i></a>

							<a href="{{ route('admin.posts.edit', $post) }}"
								class="btn btn-xs btn-info"
							><i class="fa fa-pencil"></i></a>
							<form method="POST"
								action="{{ route('admin.posts.destroy', $post) }}"
								style="display: inline">
								{{ csrf_field() }} {{ method_field('DELETE') }}
								<button class="btn btn-xs btn-danger"
									onclick="return confirm('¿Estás seguro de querer eliminar esta publicación?')"
								><i class="fa fa-times"></i></button>
							</form>
						</td>
					</tr>
				@endforeach
			</tbody>
		</table>
	</div>
	<!-- /.box-body -->
</div>
<!-- /.box -->
@stop

@push('styles')
	<link rel="stylesheet" href="/adminlte/plugins/datatables/dataTables.bootstrap.css">
@endpush

@push('scripts')
	<script src="/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
	<script src="/adminlte/plugins/datatables/dataTables.bootstrap.min.js"></script>
	<script>
		$(function () {
			$("#posts-table").DataTable();
		});
	</script>
@endpush